name: Dockerized App Deployment

on:
  push:
    branches: ['test01']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
    
    - name: Build and push Docker image
      run: |
        docker build -t kimyu0218/magicConch:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push kimyu0218/magicConch:latest

    - name: Deploy to Naver Cloud Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/web09-MagicConch/ && git pull origin dev
          docker-compose -f ~/web09-MagicConch/docker-compose.yml up -d

    - name: Install and Reload NGINX on the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo systemctl start nginx
          sudo systemctl enable nginx
          sudo systemctl reload nginx

    - name: Notify deployment success
      if: success()
      run: echo "Deployment successful!"
